---
# some created directories may be redundant, but are kept in case anything else
# changes, and to enable the picking and choosing of components/roles.
- name: create consul configuration directory
  sudo: yes
  file:
    path: /etc/consul
    state: directory
    mode: 0770
  tags:
    - consul
    - distributive
    - marathon

- name: create distributive marathon checklist
  sudo: yes
  copy:
    force: yes
    src: distributive-checks.json
    dest: /etc/distributive.d/marathon.json
  tags:
    - consul
    - distributive
    - marathon

- name: register distributive tests with consul
  sudo: yes
  copy:
    src: distributive-marathon-check.json
    dest: /etc/consul/
  notify:
    - reload consul
  tags:
    - consul
    - distributive
    - marathon
