---
- name: warn about deprecation
  debug:
    msg: WARNING! haproxy is deprecated and will be removed in a future version of Mantl. Please migrate to traefik at your earliest convenience.
  tags:
    - haproxy

- name: ensure haproxy docker image is present
  sudo: yes
  command: /usr/bin/docker pull {{ haproxy_image }}:{{ haproxy_image_tag }}
  tags:
    - haproxy
    - bootstrap

- name: set haproxy environment
  sudo: yes
  template:
    src: haproxy.j2
    dest: /etc/default/haproxy
  notify:
    - restart haproxy
  tags:
    - haproxy

- name: configure haproxy
  sudo: yes
  template:
    src: haproxy.service.j2
    dest: /usr/lib/systemd/system/haproxy.service
  notify:
    - reload haproxy
    - restart haproxy
  tags:
    - haproxy

- include: distributive.yml
