---
- name: update security.yml with agent_token
  connection: local
  run_once: yes
  lineinfile:
    dest: security.yml
    line: 'consul_agent_acl_token: {{ consul_agent_token }},'
    regexp: '.*consul_agent_acl_token.*'
    insertbefore: "^consul_acl_master_token"
  tags:
    - consul

- name: update acl file with agent_token
  sudo: yes
  template:
    src: acl.json.j2
    dest: /etc/consul/acl.json
  tags:
    - consul

- include: reload_consul.yml
  
