---
# check security
- hosts: localhost
  gather_facts: no
  tasks:
    - name: check for security
      when: security_enabled is not defined or not security_enabled
      fail:
        msg: |
          Security is not enabled. Please run `security-setup` in the root
          directory and re-run this playbook with the `--extra-vars`/`-e` option           pointing to your `security.yml` (like `-e @security.yml`)

- include: provision-openstack.yml

- hosts: all
  roles:
    - common

- hosts: all
  gather_facts: no
  roles:
    - consul-template

- hosts: all
  gather_facts: no
  roles:
    - docker

- hosts: all
  gather_facts: no
  roles:
    - dnsmasq

- hosts: all
  gather_facts: no
  roles:
    - nginx

- hosts: all
  gather_facts: no
  roles:
    - consul

- hosts: all
  gather_facts: no
  roles:
    - registrator

- include: playbooks/consul-join-wan.yml

- hosts: dc1:&zookeeper_servers
  gather_facts: no
  roles:
    - zookeeper

- hosts: dc1:&mesos_leaders
  gather_facts: no
  roles:
    - mesos

- hosts: dc1:&mesos_followers
  gather_facts: no
  roles:
    - mesos

- hosts: dc1:&marathon_servers
  gather_facts: no
  roles:
    - marathon

- hosts: dc2:&zookeeper_servers
  gather_facts: no
  roles:
    - zookeeper

- hosts: dc2:&mesos_leaders
  gather_facts: no
  roles:
    - mesos

- hosts: dc2:&mesos_followers
  gather_facts: no
  roles:
    - mesos

- hosts: dc2:&marathon_servers
  gather_facts: no
  roles:
    - marathon

- hosts: dc1:&proxy_servers
  gather_facts: no
  roles:
    - haproxy

- hosts: dc2:&proxy_servers
  gather_facts: no
  roles:
    - haproxy
