---
# check security
- hosts: localhost
  gather_facts: no
  tasks:
    - name: check for security
      when: security_enabled is not defined or not security_enabled
      fail:
        msg: |
          Security is not enabled. Please run `security-setup` in the root
          directory and re-run this playbook with the `--extra-vars`/`-e` option
          pointing to your `security.yml` (e.g., `-e @security.yml`)

- include: provision-openstack.yml

- hosts: all
  roles:
    - common
    - collectd
    - logrotate
    - consul-template
    - docker
    - dnsmasq
    - nginx
    - logstash

- hosts: dc1
  gather_facts: no
  roles:
    - consul
    
- hosts: dc2
  gather_facts: no
  roles:
    - consul 

- include: playbooks/consul-join-wan.yml

- hosts: vault_servers
  gather_facts: no
  roles:
   - vault

- hosts: dc1:&zookeeper_servers
  gather_facts: no
  roles:
    - zookeeper

- hosts: dc1:&mesos_leaders
  gather_facts: no
  roles:
    - mesos

- hosts: dc1:&mesos_followers
  gather_facts: no
  roles:
    - mesos

- hosts: dc1:&marathon_servers
  gather_facts: no
  roles:
    - marathon

- hosts: dc2:&zookeeper_servers
  gather_facts: no
  roles:
    - zookeeper

- hosts: dc2:&mesos_leaders
  gather_facts: no
  roles:
    - mesos

- hosts: dc2:&mesos_followers
  gather_facts: no
  roles:
    - mesos

- hosts: dc2:&marathon_servers
  gather_facts: no
  roles:
    - marathon

- hosts: dc1:&proxy_servers
  gather_facts: no
  roles:
    - haproxy

- hosts: dc2:&proxy_servers
  gather_facts: no
  roles:
    - haproxy
