---
- name: create kubernetes config directories
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/kubernetes"
    - "/srv/kubernetes"
    - "{{ kube_manifest_dir }}"
    - "{{ kube_podmaster_dir }}"
    - "{{ kube_cert_dir }}"
    - "{{ kube_users_dir }}"
  tags:
    - kubernetes

- name: install kubernetes binaries
  sudo: yes
  yum:
    name: "{{ kubernetes_package }}"
    state: present
  tags:
    - kubernetes

- name: generate kubelet systemd unit
  sudo: yes
  template:
    src: >
      {% if 'role=control' in group_names -%}kubelet-master.service.j2
      {%- else -%}kubelet-node.service.j2{%- endif %}
    dest: /usr/lib/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - kubernetes

- name: generate kubelet kubeconfig
  sudo: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/kubernetes/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - kubernetes
  with_items:
    - "{% if 'role=control' in group_names %}master.kubeconfig{% else %}node.kubeconfig{% endif %}"

- name: enable and start kubelet service
  sudo: yes
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - kubernetes

- name: pull hyperkube docker image
  sudo: yes
  command: "docker pull {{ kube_hyperkube_image }}:{{ kube_version }}"
  register: docker_pull_result
  changed_when: docker_pull_result.stdout.find('newer') > -1
  tags:
    - kubernetes

- include: secrets.yml
  tags:
    - secrets
    - kubernetes
