---
- name: Kube-UI | Write pod file
  sudo: yes
  copy:
    src: kube-ui-rc.yaml
    dest: "{{ kube_manifest_dir }}/kube-ui-rc.yaml"
  register: kube_ui_rc_def
  when: enable_ui
  tags:
    - addons
    - kube-ui

- name: Kube-UI | Write service file
  sudo: yes
  copy:
    src: kube-ui-svc.yaml
    dest: "{{ kube_manifest_dir }}/kube-ui-svc.yaml"
  register: kube_ui_svc_def
  when: enable_ui
  tags:
    - addons
    - kube-ui

- name: Kube-UI | Create or update replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: kube-ui-v1
    filename: "{{ kube_manifest_dir }}/kube-ui-rc.yaml"
    state: "{{ kube_ui_rc_def.changed | ternary('latest','present') }}"
    config: "{{ kube_config_dir }}/kubectl.kubeconfig"
  when: enable_ui
  delegate_to: "{{ groups[master_group_name][0] }}"
  run_once: true
  tags:
    - addons
    - kube-ui

- name: Kube-UI | Create or update service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: kube-ui
    filename: "{{ kube_manifest_dir }}/kube-ui-svc.yaml"
    state: "{{ kube_ui_svc_def.changed | ternary('latest','present') }}"
    config: "{{ kube_config_dir }}/kubectl.kubeconfig"
  when: enable_ui
  delegate_to: "{{ groups[master_group_name][0] }}"
  run_once: true
  tags:
    - addons
    - kube-ui
