---
- hosts: localhost
  connection: local
  vars:
    - img_url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2c
    - tmp_dir: "{{ ansible_env.HOME }}/tmp"
    - img_file: "{{ img_url | basename }}"
    - img_name: "{{ img_file.split('.') | first }}"
    - img_type: "{{ img_file.split('.') | last }}"
  tasks:
    - name: enable epel repo
      sudo: yes
      yum:
        name: epel-release
        state: latest
        
    - name: enable openstack repo
      sudo: yes
      yum:
        name: https://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-4.noarch.rpm
        state: present

    - name: install qemu-img and python-glanceclient
      sudo: yes
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - qemu-img
        - python-glanceclient

    - name: create tmp_dir directory
      file:
        path: "{{ tmp_dir }}"
        state: directory

    - name: download image from url
      get_url:
        url: "{{ img_url }}"
        dest: "{{ tmp_dir }}/{{ img_file }}"

    - name: convert image to raw format
      command:
        qemu-img convert
        "{{ tmp_dir }}/{{ img_file }}"
        "{{ tmp_dir }}/{{ img_name }}.raw"
        creates: "{{ tmp_dir }}/{{ img_name }}.raw"

    - name: upload image to glance
      glance_image:
        auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
        login_username: "{{ lookup('env','OS_USERNAME') }}"
        login_password: "{{ lookup('env','OS_PASSWORD') }}"
        login_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
        name: "{{ img_name }}"
        file: "{{ tmp_dir }}/{{ img_name }}.raw"
        disk_format: raw
        is_public: false
        timeout: 1800
        state: present
