---
- name: upload certificates to masters
  sudo: yes
  copy:
    src: "{{ cert_syncdir.path }}/certs/{{ item }}"
    dest: "{{ kube_cert_dir }}/{{ item }}"
    group: "kube"
    mode: 0440
  with_items:
    - "ca.crt"
    - "server.crt"
    - "server.key"
    - "kubecfg.crt"
    - "kubecfg.key"
    - "kubelet.crt"
    - "kubelet.key"
  notify:
    - restart kubelet
  tags:
    - kubernetes

- name: populate users for basic auth in API
  sudo: yes
  lineinfile:
    dest: "{{ kube_users_dir }}/known_users.csv"
    create: yes
    line: '{{ item.value.pass }},{{ item.key }},{{ item.value.role }}'
  with_dict: "{{ kube_users }}"
  notify:
    - restart kubelet
  tags:
    - master
    - kubernetes
